/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ActivitiesIndexRouteImport } from './routes/activities.index'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsAssetIdRouteImport } from './routes/assets.$assetId'
import { Route as MusicIndexRouteImport } from './routes/music.index'
import { Route as MusicMusicIdRouteImport } from './routes/music.$musicId'
import { Route as MusicUploadRouteImport } from './routes/music.upload'
import { Route as ActivitiesActivityIdEditRouteImport } from './routes/activities.$activityId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/activities/new',
  path: '/activities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicIndexRoute = MusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicMusicIdRoute = MusicMusicIdRouteImport.update({
  id: '/music/$musicId',
  path: '/music/$musicId',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicUploadRoute = MusicUploadRouteImport.update({
  id: '/music/upload',
  path: '/music/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdEditRoute =
  ActivitiesActivityIdEditRouteImport.update({
    id: '/activities/$activityId/edit',
    path: '/activities/$activityId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/comments': typeof CommentsRoute
  '/tags': typeof TagsRoute
  '/users': typeof UsersRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/music/$musicId': typeof MusicMusicIdRoute
  '/music/upload': typeof MusicUploadRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/music/': typeof MusicIndexRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/comments': typeof CommentsRoute
  '/tags': typeof TagsRoute
  '/users': typeof UsersRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/music/$musicId': typeof MusicMusicIdRoute
  '/music/upload': typeof MusicUploadRoute
  '/activities': typeof ActivitiesIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/music': typeof MusicIndexRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/comments': typeof CommentsRoute
  '/tags': typeof TagsRoute
  '/users': typeof UsersRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/new': typeof ArticlesNewRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/music/$musicId': typeof MusicMusicIdRoute
  '/music/upload': typeof MusicUploadRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/music/': typeof MusicIndexRoute
  '/activities/$activityId/edit': typeof ActivitiesActivityIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/comments'
    | '/tags'
    | '/users'
    | '/activities/new'
    | '/articles/$articleId'
    | '/articles/new'
    | '/assets/$assetId'
    | '/music/$musicId'
    | '/music/upload'
    | '/activities/'
    | '/articles/'
    | '/assets/'
    | '/music/'
    | '/activities/$activityId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/comments'
    | '/tags'
    | '/users'
    | '/activities/new'
    | '/articles/$articleId'
    | '/articles/new'
    | '/assets/$assetId'
    | '/music/$musicId'
    | '/music/upload'
    | '/activities'
    | '/articles'
    | '/assets'
    | '/music'
    | '/activities/$activityId/edit'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/comments'
    | '/tags'
    | '/users'
    | '/activities/new'
    | '/articles/$articleId'
    | '/articles/new'
    | '/assets/$assetId'
    | '/music/$musicId'
    | '/music/upload'
    | '/activities/'
    | '/articles/'
    | '/assets/'
    | '/music/'
    | '/activities/$activityId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  CommentsRoute: typeof CommentsRoute
  TagsRoute: typeof TagsRoute
  UsersRoute: typeof UsersRoute
  ActivitiesNewRoute: typeof ActivitiesNewRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  MusicMusicIdRoute: typeof MusicMusicIdRoute
  MusicUploadRoute: typeof MusicUploadRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  MusicIndexRoute: typeof MusicIndexRoute
  ActivitiesActivityIdEditRoute: typeof ActivitiesActivityIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/activities/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/': {
      id: '/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof MusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/$musicId': {
      id: '/music/$musicId'
      path: '/music/$musicId'
      fullPath: '/music/$musicId'
      preLoaderRoute: typeof MusicMusicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/upload': {
      id: '/music/upload'
      path: '/music/upload'
      fullPath: '/music/upload'
      preLoaderRoute: typeof MusicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$activityId/edit': {
      id: '/activities/$activityId/edit'
      path: '/activities/$activityId/edit'
      fullPath: '/activities/$activityId/edit'
      preLoaderRoute: typeof ActivitiesActivityIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  CommentsRoute: CommentsRoute,
  TagsRoute: TagsRoute,
  UsersRoute: UsersRoute,
  ActivitiesNewRoute: ActivitiesNewRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  MusicMusicIdRoute: MusicMusicIdRoute,
  MusicUploadRoute: MusicUploadRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  MusicIndexRoute: MusicIndexRoute,
  ActivitiesActivityIdEditRoute: ActivitiesActivityIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
