patchedDependencies:
  '@vue/shared': patches/@vue__shared.patch
catalog:
  '@antfu/eslint-config': ^4.17.0
  '@iconify-json/lucide': ^1.2.57
  '@iconify-json/mingcute': ^1.2.3
  '@iconify-json/svg-spinners': ^1.2.2
  '@nuxt/content': ^3.6.3
  '@nuxt/icon': ^1.15.0
  '@nuxt/image': ^1.10.0
  '@nuxtjs/color-mode': ^3.5.2
  '@nuxtjs/google-fonts': ^3.2.0
  '@nuxtjs/seo': ^3.1.0
  '@pinia/nuxt': ^0.11.2
  '@prisma/client': ^6.12.0
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/vite': ^4.1.11
  '@types/bcrypt': ^5.0.2
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^24.0.14
  '@types/throttle-debounce': ^5.0.2
  '@types/vivus': ^0.4.7
  '@vueuse/core': ^13.5.0
  '@vueuse/nuxt': ^13.5.0
  bcrypt: ^6.0.0
  clipboard: ^2.0.11
  dayjs: ^1.11.13
  dotenv: ^17.2.0
  eslint: ^9.31.0
  feed: ^5.1.0
  gsap: ^3.13.0
  hana-img-viewer: ^1.2.3
  jsonwebtoken: ^9.0.2
  nuxt: ^4.0.0
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.4.1
  prisma: ^6.12.0
  tailwindcss: ^4.1.11
  throttle-debounce: ^5.0.2
  typescript: ~5.8.3
  vivus: ^0.4.6
  vue: ^3.5.17
  vue-router: ^4.5.1
  zod: ^4.0.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@pkgr/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - synckit
  - unrs-resolver
  - vue-demi
