catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
  - semver@6.3.1

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@iconify-json/lucide': ^1.2.82
  '@iconify-json/mingcute': ^1.2.6
  '@iconify-json/svg-spinners': ^1.2.4
  '@nuxt/content': ^3.10.0
  '@nuxt/icon': ^2.1.1
  '@nuxt/image': ^2.0.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/mdc': ^0.19.2
  '@nuxtjs/seo': ^3.3.0
  '@pinia/nuxt': ^0.11.3
  '@prisma/client': 6.19.0
  '@types/bcrypt': ^6.0.0
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^25.0.3
  '@types/throttle-debounce': ^5.0.2
  '@types/vivus': ^0.4.7
  '@unocss/eslint-plugin': ^66.5.11
  '@unocss/nuxt': ^66.5.11
  '@unocss/preset-rem-to-px': ^66.5.11
  '@unocss/reset': ^66.5.11
  '@vueuse/core': ^14.1.0
  '@vueuse/nuxt': ^14.1.0
  '@vueuse/router': ^14.1.0
  baseline-browser-mapping: ^2.9.11
  bcrypt: ^6.0.0
  better-sqlite3: ^12.5.0
  clipboard: ^2.0.11
  dayjs: ^1.11.19
  dotenv: ^17.2.3
  eslint: ^9.39.2
  feed: ^5.1.0
  gsap: ^3.14.2
  hana-img-viewer: ^1.2.9
  jsonwebtoken: ^9.0.3
  lucide-vue-next: ^0.562.0
  nuxt: ^4.2.2
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  prisma: 6.19.0
  resend: ^6.6.0
  sass-embedded: ^1.97.1
  throttle-debounce: ^5.0.2
  typescript: ^5.9.3
  unocss: ^66.5.11
  unocss-preset-scrollbar: ^3.2.0
  vivus: ^0.4.6
  vue: ^3.5.26
  vue-component-type-helpers: ^3.2.1
  vue-router: ^4.6.4
  zod: ^4.2.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
