catalog:
  '@antfu/eslint-config': ^5.2.0
  '@iconify-json/lucide': ^1.2.61
  '@iconify-json/mingcute': ^1.2.3
  '@iconify-json/svg-spinners': ^1.2.2
  '@nuxt/content': ^3.6.3
  '@nuxt/fonts': ^0.11.4
  '@nuxt/icon': ^1.15.0
  '@nuxt/image': ^1.11.0
  '@nuxtjs/color-mode': ^3.5.2
  '@nuxtjs/seo': ^3.1.0
  '@pinia/nuxt': ^0.11.2
  '@prisma/client': ^6.13.0
  '@types/bcrypt': ^6.0.0
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^24.2.0
  '@types/nodemailer': ^6.4.17
  '@types/throttle-debounce': ^5.0.2
  '@types/vivus': ^0.4.7
  '@unocss/eslint-plugin': ^66.4.2
  '@unocss/nuxt': ^66.4.2
  '@unocss/preset-rem-to-px': ^66.4.2
  '@unocss/reset': ^66.4.2
  '@vueuse/core': ^13.6.0
  '@vueuse/nuxt': ^13.6.0
  bcrypt: ^6.0.0
  clipboard: ^2.0.11
  dayjs: ^1.11.13
  dotenv: ^17.2.1
  eslint: ^9.32.0
  feed: ^5.1.0
  gsap: ^3.13.0
  hana-img-viewer: ^1.2.3
  jsonwebtoken: ^9.0.2
  nodemailer: ^7.0.5
  nuxt: ^4.0.3
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.4.1
  prisma: ^6.13.0
  throttle-debounce: ^5.0.2
  typescript: ^5.9.2
  unocss: ^66.4.2
  unocss-preset-scrollbar: ^3.2.0
  vivus: ^0.4.6
  vue: ^3.5.18
  vue-router: ^4.5.1
  zod: ^4.0.15

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@pkgr/core'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - synckit
  - unrs-resolver
  - vue-demi
