catalog:
  '@antfu/eslint-config': ^4.13.2
  '@iconify-json/lucide': ^1.2.44
  '@iconify-json/mingcute': ^1.2.3
  '@iconify-json/svg-spinners': ^1.2.2
  '@nuxt/content': ^3.5.1
  '@nuxt/icon': ^1.13.0
  '@nuxt/image': ^1.10.0
  '@nuxtjs/color-mode': ^3.5.2
  '@nuxtjs/google-fonts': ^3.2.0
  '@nuxtjs/seo': 3.0.3
  '@pinia/nuxt': ^0.11.0
  '@prisma/client': ^6.8.2
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/vite': ^4.1.7
  '@types/bcrypt': ^5.0.2
  '@types/jsonwebtoken': ^9.0.9
  '@types/node': ^22.15.21
  '@types/vivus': ^0.4.7
  '@vueuse/core': ^13.2.0
  '@vueuse/nuxt': ^13.2.0
  bcrypt: ^6.0.0
  clipboard: ^2.0.11
  dayjs: ^1.11.13
  dotenv: ^16.5.0
  eslint: ^9.27.0
  feed: ^5.0.1
  gsap: ^3.13.0
  hana-img-viewer: ^1.2.2
  jsonwebtoken: ^9.0.2
  nuxt: ^3.17.4
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.3.0
  prisma: 6.8.2
  tailwindcss: ^4.1.7
  typescript: ~5.8.3
  vivus: ^0.4.6
  vue: latest
  vue-router: latest
  zod: ^3.25.13
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - vue-demi
