catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
  - semver@6.3.1

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@iconify-json/lucide': ^1.2.90
  '@nuxt/content': ^3.11.2
  '@nuxt/icon': ^2.2.1
  '@nuxt/image': ^2.0.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/mdc': ^0.20.1
  '@nuxtjs/seo': ^3.4.0
  '@pinia/nuxt': ^0.11.3
  '@prisma/adapter-pg': ^7.4.0
  '@prisma/client': ^7.4.0
  '@types/bcrypt': ^6.0.0
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^25.2.3
  '@types/vivus': ^0.4.7
  '@unocss/eslint-plugin': ^66.6.0
  '@unocss/nuxt': ^66.6.0
  '@unocss/preset-rem-to-px': ^66.6.0
  '@unocss/reset': ^66.6.0
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.2.1
  '@vueuse/router': ^14.2.1
  bcrypt: ^6.0.0
  clipboard: ^2.0.11
  dayjs: ^1.11.19
  dotenv: ^17.2.4
  eslint: 9.39.2
  feed: ^5.2.0
  gsap: ^3.14.2
  hana-img-viewer: ^2.0.2
  jsonwebtoken: ^9.0.3
  lucide-vue-next: ^0.563.0
  nuxt: ^4.3.1
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  prisma: ^7.4.0
  resend: ^6.9.2
  sass-embedded: ^1.97.3
  typescript: ^5.9.3
  unocss: ^66.6.0
  unocss-preset-scrollbar: ^3.2.0
  vivus: ^0.4.6
  vue: ^3.5.28
  vue-router: ^5.0.2
  zod: ^4.3.6

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - bcrypt
  - esbuild
  - prisma
  - sharp

peerDependencyRules:
  allowedVersions:
    '@unhead/vue': '2'
    citty: '0.2'
    magicast: '0.5'
