catalog:
  '@antfu/eslint-config': ^6.2.0
  '@iconify-json/lucide': ^1.2.75
  '@iconify-json/mingcute': ^1.2.5
  '@iconify-json/svg-spinners': ^1.2.4
  '@nuxt/content': ^3.8.2
  '@nuxt/icon': ^2.1.0
  '@nuxt/image': ^2.0.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/seo': ^3.2.2
  '@pinia/nuxt': ^0.11.3
  '@prisma/client': 6.19.0
  '@types/bcrypt': ^6.0.0
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^24.10.1
  '@types/throttle-debounce': ^5.0.2
  '@types/vivus': ^0.4.7
  '@unocss/eslint-plugin': ^66.5.9
  '@unocss/nuxt': ^66.5.9
  '@unocss/preset-rem-to-px': ^66.5.9
  '@unocss/reset': ^66.5.9
  '@vueuse/core': ^14.0.0
  '@vueuse/nuxt': ^14.0.0
  '@vueuse/router': ^14.0.0
  bcrypt: ^6.0.0
  better-sqlite3: ^12.4.6
  clipboard: ^2.0.11
  dayjs: ^1.11.19
  dotenv: ^17.2.3
  eslint: ^9.39.1
  feed: ^5.1.0
  gsap: ^3.13.0
  hana-img-viewer: ^1.2.9
  jsonwebtoken: ^9.0.2
  lucide-vue-next: ^0.554.0
  nuxt: ^4.2.1
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  prisma: 6.19.0
  resend: ^6.5.2
  sass-embedded: ^1.93.3
  throttle-debounce: ^5.0.2
  typescript: ^5.9.3
  unocss: ^66.5.9
  unocss-preset-scrollbar: ^3.2.0
  vivus: ^0.4.6
  vue: ^3.5.25
  vue-component-type-helpers: 3.0.1
  vue-router: ^4.6.3
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
