allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  vue-demi: true

catalogMode: prefer
cleanupUnusedCatalogs: true

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
  - semver@6.3.1

catalog:
  '@antfu/eslint-config': ^9.1.0
  '@lucide/vue': ^1.22.0
  '@nuxt/fonts': ^0.14.0
  '@nuxt/image': ^2.0.0
  '@nuxtjs/color-mode': ^4.0.1
  '@nuxtjs/mdc': ^0.22.0
  '@nuxtjs/seo': ^5.3.1
  '@pinia/nuxt': ^0.11.3
  '@prisma/adapter-pg': ^7.8.0
  '@prisma/client': ^7.8.0
  '@takumi-rs/core': ^1.8.7
  '@types/jsonwebtoken': ^9.0.10
  '@types/node': ^26.0.1
  '@types/vivus': ^0.4.7
  '@unocss/eslint-plugin': ^66.7.4
  '@unocss/nuxt': ^66.7.4
  '@unocss/preset-rem-to-px': ^66.7.4
  '@unocss/reset': ^66.7.4
  '@vueuse/core': ^14.3.0
  '@vueuse/nuxt': ^14.3.0
  '@vueuse/router': ^14.3.0
  bcryptjs: ^3.0.2
  dotenv: ^17.4.2
  eslint: ^10.6.0
  feed: ^5.2.1
  gsap: ^3.15.0
  hana-img-viewer: ^4.0.0
  jose: ^6.2.3
  nuxt: ^4.4.8
  nuxt-og-image: ^6.7.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  prisma: ^7.8.0
  rehype-sanitize: 6.0.0
  resend: ^6.16.0
  typescript: ^6.0.3
  unocss: ^66.7.4
  unocss-preset-scrollbar: ^4.0.0
  vivus: ^0.4.6
  vue: ^3.5.39
  vue-router: ^5.1.0
  zod: ^4.4.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - vue-demi
peerDependencyRules:
  allowedVersions:
    '@unhead/vue': '2'
    citty: '0.2'
    magicast: '0.5'
