name: Deploy to VPS

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: vps-deploy
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          HANA_DATABASE_URL: ${{ secrets.HANA_DATABASE_URL }}

      - name: Build (Nuxt)
        run: pnpm build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          HANA_DATABASE_URL: ${{ secrets.HANA_DATABASE_URL }}

      - name: Prepare artifact directory
        run: |
          mkdir -p .deploy
          cp -r .output .deploy/.output
          cp ecosystem.config.cjs .deploy/

      - name: Upload build artifacts to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: ".deploy/**"
          target: "${{ secrets.APP_DIR }}"
          overwrite: true

      - name: Apply DB migrations and reload PM2 (zero-downtime)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          envs: VPS_DIR
          script: |
            set -e
            mkdir -p "$VPS_DIR"
            cd "$VPS_DIR"
            if [ -d .output ]; then rm -rf .output; fi
            if [ -f ecosystem.config.cjs ]; then rm -f ecosystem.config.cjs; fi
            mv .deploy/.output ./
            mv .deploy/ecosystem.config.cjs ./
            rm -rf .deploy

            if pm2 describe grey-flowers >/dev/null 2>&1; then
              pm2 reload grey-flowers --update-env
            else
              pm2 startOrReload ecosystem.config.cjs --update-env
            fi
            pm2 save
        env:
          VPS_DIR: ${{ secrets.APP_DIR }}
